### ISSUE TITLE
Can't load data! Error!

### ISSUE THREAD

**Issue by ghost** [markoblad/forbes-hackathon#1]
I am trying load the list of billionaires in 2016 and it says that 403 forbidden.
This is my code

``````
var url = "http://apis.forbes.com/hackathon/person/billionaires/{2016}/position/true.json?start={1}&limit={10}&fields=name,age,source,residence,countryOfCitizenship,person&api_key=gxgpvwxya25quemzxh9r5593";

    $.getJSON(url, function (data) {
      console.log(data);
    }); ```

Also tried with a callback after the url like this ``` + "?callback=? " ```
Thanks in advance.
``````

**Comment by markoblad** [comment]
I would have expected Forbes to have pulled this api down and inactivate this particular developer key after the hackathon.  This returns "developer inactive" for the key:

`http://apis.forbes.com/hackathon/person/billionaires/2016/position/true.json?start=1&limit=10&fields=name,age,source,residence,countryOfCitizenship,person&api_key=gxgpvwxya25quemzxh9r5593`

Check with the forbes folks to see if they have anything opened.
